export const words = [
    { "english": "loop", "hebrew": "לולאה" , "pronouncs": "lola'a"},
    { "english": "boy", "hebrew": "ילד" , "pronouncs": "yaled"},
    { "english": "water", "hebrew": "מים", "pronouncs": "mayem"},
    { "english": "king", "hebrew": "מלך", "pronouncs": "melech" },
    { "english": "grandson", "hebrew": "נכד", "pronouncs": "neched" },
    { "english": "horse", "hebrew": "סוס", "pronouncs": "sus" },
    { "english": "work(n)", "hebrew": "עבודה", "pronouncs": "avodah" },
    { "english": "big", "hebrew": "גדול", "pronouncs": "gadol" },
    { "english": "elephant", "hebrew": "פיל", "pronouncs": "pil" },
    { "english": "end", "hebrew": "סוף", "pronouncs": "sof" },
    { "english": "saint", "hebrew": "צדיק", "pronouncs": "tzadik" },
    { "english": "bird", "hebrew": "ציפור", "pronouncs": "tzipor" },
    { "english": "roof", "hebrew": "גג", "pronouncs": "gag" },
    { "english": "fish", "hebrew": "דג", "pronouncs": "dag" },
    { "english": "water heater", "hebrew": "דוד", "pronouncs": "dud" },
    { "english": "fly(insect)", "hebrew": "זבוב", "pronouncs": "zvuv" },
    { "english": "farm", "hebrew": "חווה", "pronouncs": "chava" },
    { "english": "hand", "hebrew": "די", "pronouncs": "yad" },
    { "english": "start", "hebrew": "כוכב", "pronouncs": "kochav" },
    { "english": "time", "hebrew": "זמן", "pronouncs": "zman" },
    { "english": "first", "hebrew": "ראשון", "pronouncs": "reshon" },
    { "english": "parents", "hebrew": "הורים", "pronouncs": "horim" },
    { "english": "clothes", "hebrew": "בגדים", "pronouncs": "bgadim" },
    { "english": "book", "hebrew": "ספר", "pronouncs": "sefer" },
    { "english": "lord god", "hebrew": "יהוה", "pronouncs": "adonai" },
    { "english": "room", "hebrew": "חדר", "pronouncs": "cheder" },
    { "english": "friend", "hebrew": "חבר", "pronouncs": "chaver" },
    { "english": "comfortable", "hebrew": "נוח", "pronouncs": "noach" },
    { "english": "happy", "hebrew": "שמח", "pronouncs": "sameach" },
    { "english": "sad", "hebrew": "עצוב", "pronouncs": "aatzov" },
    { "english": "black", "hebrew": "שחור", "pronouncs": "shachor" },
    { "english": "white", "hebrew": "לבן", "pronouncs": "lavan" },
    { "english": "hot", "hebrew": "חם", "pronouncs": "cham" },
    { "english": "cold", "hebrew": "קר", "pronouncs": "kar" },
    { "english": "strong", "hebrew": "חזק", "pronouncs": "chazak" },
    { "english": "weak", "hebrew": "חלש", "pronouncs": "chalash" },
    { "english": "long", "hebrew": "ארוך", "pronouncs": "aroch" },
    { "english": "short", "hebrew": "קצר", "pronouncs": "ketzar" },
    { "english": "healthy", "hebrew": "בריא", "pronouncs": "bari" },
    { "english": "sick", "hebrew": "חולה", "pronouncs": "choleh" },
    { "english": "expensive", "hebrew": "יקר", "pronouncs": "yakar" },
    { "english": "cheap", "hebrew": "זול", "pronouncs": "zol" },
    { "english": "slim", "hebrew": "רזה", "pronouncs": "razeh" },
    { "english": "fat", "hebrew": "שמן", "pronouncs": "shemen" },
    { "english": "new", "hebrew": "חדש", "pronouncs": "chadash" },
    { "english": "old", "hebrew": "ישן", "pronouncs": "yshan" },
    { "english": "sweet", "hebrew": "מתוק", "pronouncs": "matok" },
    { "english": "salty", "hebrew": "מלוח", "pronouncs": "maloach" },
    { "english": "tall/high", "hebrew": "גבוה", "pronouncs": "gavoah" },
    { "english": "low", "hebrew": "נמוך", "pronouncs": "namuch" },
    { "english": "(he) eat", "hebrew": "אוכל", "pronouncs": "ochel" },
    { "english": "(he) drink", "hebrew": "שותה", "pronouncs": "shoteh" },
    { "english": "(he) live", "hebrew": "גר", "pronouncs": "gar" },
    { "english": "(he) study", "hebrew": "לומד", "pronouncs": "lomed" },
    { "english": "(he) talk/speak", "hebrew": "מדבר", "pronouncs": "medaber" },
    { "english": "(he) do/make", "hebrew": "עושה", "pronouncs": "oseh" },
    { "english": "(he) read/call", "hebrew": "קורא", "pronouncs": "koreh" },
    { "english": "(he) think", "hebrew": "חושב", "pronouncs": "choshev" },
    { "english": "(he) write", "hebrew": "כותב", "pronouncs": "kotev" },
    { "english": "(he) understand", "hebrew": "מבין", "pronouncs": "mevin" },
    { "english": "(he) want", "hebrew": "רוצה", "pronouncs": "rotzeh" },
    { "english": "(he) ask", "hebrew": "שואל", "pronouncs": "sho'el" },
    { "english": "(he) say", "hebrew": "אומר", "pronouncs": "omer" },
    { "english": "(he) count", "hebrew": "סופר", "pronouncs": "sofer" },
    { "english": "(he) go/walk", "hebrew": "הולך", "pronouncs": "holech" },
    { "english": "(he) return", "hebrew": "חוזר", "pronouncs": "chozech" },
    { "english": "(he) drive/ride/travel", "hebrew": "נוסע", "pronouncs": "noseaa" },
    { "english": "(he) run", "hebrew": "רץ", "pronouncs": "ratz" },
    { "english": "(he) (get/wake) up", "hebrew": "קם", "pronouncs": "kam" },
    { "english": "(he) hear", "hebrew": "שומע", "pronouncs": "shomeaa" },
    { "english": "(he) come", "hebrew": "בא", "pronouncs": "ba" },
    { "english": "(he) invite/order", "hebrew": "מזמין", "pronouncs": "mazmin" },
    { "english": "(he) feel", "hebrew": "מרגיש", "pronouncs": "margish" },
    { "english": "(he) see", "hebrew": "רואה", "pronouncs": "ro'eh" },
    { "english": "(he) dance", "hebrew": "רוקד", "pronouncs": "roked" },
    { "english": "(he) sind", "hebrew": "שר", "pronouncs": "shar" },
    { "english": "(he) request", "hebrew": "מבקש", "pronouncs": "mevakesh" },
    { "english": "(he) give", "hebrew": "נותן", "pronouncs": "noten" },
    { "english": "(he) meet", "hebrew": "פוגש", "pronouncs": "pogesh" },
    { "english": "(he) can", "hebrew": "יכול", "pronouncs": "yachol" },
    { "english": "(he) hurt/pain", "hebrew": "כואב", "pronouncs": "ko'ev" },
    { "english": "(he) rest", "hebrew": "נח", "pronouncs": "nach" },
    { "english": "(he) choose", "hebrew": "בוחר", "pronouncs": "bocher" },
    { "english": "(he) waer", "hebrew": "לובש", "pronouncs": "lovesh" },
    { "english": "(he) find", "hebrew": "מוצא", "pronouncs": "motze" },
    { "english": "(he) dream", "hebrew": "חולם", "pronouncs": "cholem" },
    { "english": "(he) open", "hebrew": "פותח", "pronouncs": "poteach" },
    { "english": "(he) close", "hebrew": "סוגר", "pronouncs": "soger" },
    { "english": "(he) stand", "hebrew": "עומד", "pronouncs": "omed" },
    { "english": "(he) buy", "hebrew": "קונה", "pronouncs": "koneh" },
    { "english": "(he) put", "hebrew": "שם", "pronouncs": "sam" },
    { "english": "(he) build", "hebrew": "בונה", "pronouncs": "boneh" },
    { "english": "(he) go up/rise", "hebrew": "עולה", "pronouncs": "oleh" },
    { "english": "(he) go down", "hebrew": "יורד", "pronouncs": "yored" },
    { "english": "(he) answer", "hebrew": "עונה", "pronouncs": "oneh" },
    { "english": "(he) exit/leave", "hebrew": "יוצא", "pronouncs": "yotze" },
    { "english": "(he) take", "hebrew": "לוקח", "pronouncs": "lokeach" },
    { "english": "(he) sit", "hebrew": "יושב", "pronouncs": "yoshev" },
    { "english": "(he) pray", "hebrew": "מתפלל", "pronouncs": "metpalel" },
    { "english": "(he) play music", "hebrew": "מנגן", "pronouncs": "menagen" },
    { "english": "(he) organize/arrange", "hebrew": "מסדר", "pronouncs": "mesader" },
    { "english": "(he) tell a story", "hebrew": "מספר", "pronouncs": "mesaper" },
    { "english": "(he) photograph/film", "hebrew": "מצלם", "pronouncs": "metzalem" },
    { "english": "(he) play", "hebrew": "משחק", "pronouncs": "mesachek" },
    { "english": "(he) arrive", "hebrew": "מגיע", "pronouncs": "magiaa" },
    { "english": "(he) argue", "hebrew": "רב", "pronouncs": "rav" },
    { "english": "(he) fly (airplane)", "hebrew": "טס", "pronouncs": "tas" },
    { "english": "money/silver", "hebrew": "כסף", "pronouncs": "kesef" },
    { "english": "but", "hebrew": "אבל", "pronouncs": "aval" },
    { "english": "now", "hebrew": "עכשיו", "pronouncs": "achshav" },
    { "english": "people", "hebrew": "אנשים", "pronouncs": "anashim" },
    { "english": "here", "hebrew": "פה/כן", "pronouncs": "pu/kan" },
    { "english": "lot", "hebrew": "הרבה", "pronouncs": "harbeh" },
    { "english": "children", "hebrew": "ילדים", "pronouncs": "yeladim" },
    { "english": "at all", "hebrew": "בכלל", "pronouncs": "bechlal" },
    { "english": "apartment", "hebrew": "דירה", "pronouncs": "dira" },
    { "english": "stuff", "hebrew": "דברים", "pronouncs": "dvarim" },
    { "english": "store", "hebrew": "חנות", "pronouncs": "chanut" },
    { "english": "next to", "hebrew": "ליד", "pronouncs": "liad" },
    { "english": "plan/program", "hebrew": "תוכנית", "pronouncs": "tochnit" },
    { "english": "tomorrow", "hebrew": "מחר", "pronouncs": "machar" },
    { "english": "cat", "hebrew": "חתול", "pronouncs": "chatul" },
    { "english": "very", "hebrew": "מאוד", "pronouncs": "me'od" },
    { "english": "car", "hebrew": "מכונית", "pronouncs": "mechonit" },
    { "english": "never", "hebrew": "אף פעם", "pronouncs": "af paam" },
    { "english": "enough", "hebrew": "מספיק", "pronouncs": "maspik" },
    { "english": "question", "hebrew": "שאלה", "pronouncs": "she'elah" },
    { "english": "tired", "hebrew": "עיף", "pronouncs": "aaif" },
    { "english": "yesterday", "hebrew": "אתמול", "pronouncs": "etmol" },
    { "english": "day before yesterday", "hebrew": "שלשום", "pronouncs": "shelshom" },
    { "english": "how long", "hebrew": "כמה זמן", "pronouncs": "kama zman" },
    { "english": "there", "hebrew": "שם", "pronouncs": "sham" },
    { "english": "day", "hebrew": "יום", "pronouncs": "yom" },
    { "english": "after", "hebrew": "אחרי", "pronouncs": "acharei" },
    { "english": "in/while/(after a period of time)", "hebrew": "בעוד", "pronouncs": "be'od" },
    { "english": "vacation", "hebrew": "חופשה", "pronouncs": "chofsha" },
    { "english": "event", "hebrew": "אירוע", "pronouncs": "eroaa" },
    { "english": "half", "hebrew": "חצי", "pronouncs": "chetzi" },
]

