export const words = [
    { "english": "loop", "hebrew": "לולאה" , "pronouncs": "lola'a"},
    { "english": "boy", "hebrew": "ילד" , "pronouncs": "yaled"},
    { "english": "water", "hebrew": "מים", "pronouncs": "mayem"},
    { "english": "king", "hebrew": "מלך", "pronouncs": "melech" },
    { "english": "grandson", "hebrew": "נכד", "pronouncs": "neched" },
    { "english": "horse", "hebrew": "סוס", "pronouncs": "sus" },
    { "english": "work(n)", "hebrew": "עבודה", "pronouncs": "avodah" },
    { "english": "big", "hebrew": "גדול", "pronouncs": "gadol" },
    { "english": "elephant", "hebrew": "פיל", "pronouncs": "pil" },
    { "english": "end", "hebrew": "סוף", "pronouncs": "sof" },
    { "english": "saint", "hebrew": "צדיק", "pronouncs": "tsadik" },
    { "english": "bird", "hebrew": "ציפור", "pronouncs": "tsipor" },
    { "english": "roof", "hebrew": "גג", "pronouncs": "gag" },
    { "english": "fish", "hebrew": "דג", "pronouncs": "dag" },
    { "english": "water heater", "hebrew": "דוד", "pronouncs": "dud" },
    { "english": "fly(insect)", "hebrew": "זבוב", "pronouncs": "zvuv" },
    { "english": "farm", "hebrew": "חווה", "pronouncs": "chava" },
    { "english": "hand", "hebrew": "די", "pronouncs": "yad" },
    { "english": "start", "hebrew": "כוכב", "pronouncs": "kochav" },
    { "english": "time", "hebrew": "זמן", "pronouncs": "zman" },
    { "english": "first", "hebrew": "ראשון", "pronouncs": "reshon" },
    { "english": "parents", "hebrew": "הורים", "pronouncs": "horim" },
    { "english": "clothes", "hebrew": "בגדים", "pronouncs": "bgadim" },
    { "english": "book", "hebrew": "ספר", "pronouncs": "sefer" },
    { "english": "lord god", "hebrew": "יהוה", "pronouncs": "adonai" },
    { "english": "room", "hebrew": "חדר", "pronouncs": "cheder" },
    { "english": "friend", "hebrew": "חבר", "pronouncs": "chaver" },
    { "english": "comfortable", "hebrew": "נוח", "pronouncs": "noach" },
    { "english": "happy", "hebrew": "שמח", "pronouncs": "sameach" },
    { "english": "sad", "hebrew": "עצוב", "pronouncs": "aatsov" },
    { "english": "black", "hebrew": "שחור", "pronouncs": "shachor" },
    { "english": "white", "hebrew": "לבן", "pronouncs": "lavan" },
    { "english": "hot", "hebrew": "חם", "pronouncs": "cham" },
    { "english": "cold", "hebrew": "קר", "pronouncs": "kar" },
    { "english": "strong", "hebrew": "חזק", "pronouncs": "chazak" },
    { "english": "weak", "hebrew": "חלש", "pronouncs": "chalash" },
    { "english": "long", "hebrew": "ארוך", "pronouncs": "aroch" },
    { "english": "short", "hebrew": "קצר", "pronouncs": "ketsar" },
    { "english": "healthy", "hebrew": "בריא", "pronouncs": "bari" },
    { "english": "sick", "hebrew": "חולה", "pronouncs": "choleh" },
    { "english": "expensive", "hebrew": "יקר", "pronouncs": "yakar" },
    { "english": "cheap", "hebrew": "זול", "pronouncs": "zol" },
    { "english": "slim", "hebrew": "רזה", "pronouncs": "razeh" },
    { "english": "fat", "hebrew": "שמן", "pronouncs": "shemen" },
    { "english": "new", "hebrew": "חדש", "pronouncs": "chadash" },
    { "english": "old", "hebrew": "ישן", "pronouncs": "yshan" },
    { "english": "sweet", "hebrew": "מתוק", "pronouncs": "matok" },
    { "english": "salty", "hebrew": "מלוח", "pronouncs": "maloach" },
    { "english": "tall/high", "hebrew": "גבוה", "pronouncs": "gavoah" },
    { "english": "low", "hebrew": "נמוך", "pronouncs": "namuch" },
    { "english": "(he) eat", "hebrew": "אוכל", "pronouncs": "ochel" },
    { "english": "(he) drink", "hebrew": "שותה", "pronouncs": "shoteh" },
    { "english": "(he) live", "hebrew": "גר", "pronouncs": "gar" },
    { "english": "(he) study", "hebrew": "לומד", "pronouncs": "lomed" },
    { "english": "(he) talk/speak", "hebrew": "מדבר", "pronouncs": "medaber" },
    { "english": "(he) do/make", "hebrew": "עושה", "pronouncs": "oseh" },
    { "english": "(he) read/call", "hebrew": "קורא", "pronouncs": "koreh" },
    { "english": "(he) think", "hebrew": "חושב", "pronouncs": "choshev" },
    { "english": "(he) write", "hebrew": "כותב", "pronouncs": "kotev" },
    { "english": "(he) understand", "hebrew": "מבין", "pronouncs": "mevin" },
    { "english": "(he) want", "hebrew": "רוצה", "pronouncs": "rotseh" },
    { "english": "(he) ask", "hebrew": "שואל", "pronouncs": "sho'el" },
    { "english": "(he) say", "hebrew": "אומר", "pronouncs": "omer" },
    { "english": "(he) count", "hebrew": "סופר", "pronouncs": "sofer" },
    { "english": "(he) go/walk", "hebrew": "הולך", "pronouncs": "holech" },
    { "english": "(he) return", "hebrew": "חוזר", "pronouncs": "chozech" },
    { "english": "(he) drive/ride/travel", "hebrew": "נוסע", "pronouncs": "noseaa" },
    { "english": "(he) run", "hebrew": "רץ", "pronouncs": "rats" },
    { "english": "(he) (get/wake) up", "hebrew": "קם", "pronouncs": "kam" },
    { "english": "(he) hear", "hebrew": "שומע", "pronouncs": "shomeaa" },
    { "english": "(he) come", "hebrew": "בא", "pronouncs": "ba" },
    { "english": "(he) invite/order", "hebrew": "מזמין", "pronouncs": "mazmin" },
    { "english": "(he) feel", "hebrew": "מרגיש", "pronouncs": "margish" },
    { "english": "(he) see", "hebrew": "רואה", "pronouncs": "ro'eh" },
    { "english": "(he) dance", "hebrew": "רוקד", "pronouncs": "roked" },
    { "english": "(he) sind", "hebrew": "שר", "pronouncs": "shar" },
    { "english": "(he) request", "hebrew": "מבקש", "pronouncs": "mevakesh" },
    { "english": "(he) give", "hebrew": "נותן", "pronouncs": "noten" },
    { "english": "(he) meet", "hebrew": "פוגש", "pronouncs": "pogesh" },
    { "english": "(he) can", "hebrew": "יכול", "pronouncs": "yachol" },
    { "english": "(he) hurt/pain", "hebrew": "כואב", "pronouncs": "ko'ev" },
    { "english": "(he) rest", "hebrew": "נח", "pronouncs": "nach" },
    { "english": "(he) choose", "hebrew": "בוחר", "pronouncs": "bocher" },
    { "english": "(he) waer", "hebrew": "לובש", "pronouncs": "lovesh" },
    { "english": "(he) find", "hebrew": "מוצא", "pronouncs": "motse" },
    { "english": "(he) dream", "hebrew": "חולם", "pronouncs": "cholem" },
]
