export const words = [
    { "english": "loop", "hebrew": "לולאה" , "pronouncs": "lola'a"},
    { "english": "boy", "hebrew": "ילד" , "pronouncs": "yaled"},
    { "english": "water", "hebrew": "מים", "pronouncs": "mayem"},
    { "english": "king", "hebrew": "מלך", "pronouncs": "melech" },
    { "english": "grandson", "hebrew": "נכד", "pronouncs": "neched" },
    { "english": "horse", "hebrew": "סוס", "pronouncs": "sus" },
    { "english": "work(n)", "hebrew": "עבודה", "pronouncs": "avodah" },
    { "english": "big", "hebrew": "גדול", "pronouncs": "gadol" },
    { "english": "elephant", "hebrew": "פיל", "pronouncs": "pil" },
    { "english": "end", "hebrew": "סוף", "pronouncs": "sof" },
    { "english": "saint", "hebrew": "צדיק", "pronouncs": "tzadik" },
    { "english": "bird", "hebrew": "ציפור", "pronouncs": "tzipor" },
    { "english": "roof", "hebrew": "גג", "pronouncs": "gag" },
    { "english": "fish", "hebrew": "דג", "pronouncs": "dag" },
    { "english": "water heater", "hebrew": "דוד", "pronouncs": "dud" },
    { "english": "fly(insect)", "hebrew": "זבוב", "pronouncs": "zvuv" },
    { "english": "farm", "hebrew": "חווה", "pronouncs": "chava" },
    { "english": "hand", "hebrew": "די", "pronouncs": "yad" },
    { "english": "start", "hebrew": "כוכב", "pronouncs": "kochav" },
    { "english": "time", "hebrew": "זמן", "pronouncs": "zman" },
    { "english": "first", "hebrew": "ראשון", "pronouncs": "reshon" },
    { "english": "parents", "hebrew": "הורים", "pronouncs": "horim" },
    { "english": "clothes", "hebrew": "בגדים", "pronouncs": "bgadim" },
    { "english": "book", "hebrew": "ספר", "pronouncs": "sefer" },
    { "english": "lord god", "hebrew": "יהוה", "pronouncs": "adonai" },
    { "english": "room", "hebrew": "חדר", "pronouncs": "cheder" },
    { "english": "friend", "hebrew": "חבר", "pronouncs": "chaver" },
    { "english": "comfortable", "hebrew": "נוח", "pronouncs": "noach" },
    { "english": "happy", "hebrew": "שמח", "pronouncs": "sameach" },
    { "english": "sad", "hebrew": "עצוב", "pronouncs": "aatzov" },
    { "english": "black", "hebrew": "שחור", "pronouncs": "shachor" },
    { "english": "white", "hebrew": "לבן", "pronouncs": "lavan" },
    { "english": "hot", "hebrew": "חם", "pronouncs": "cham" },
    { "english": "cold", "hebrew": "קר", "pronouncs": "kar" },
    { "english": "strong", "hebrew": "חזק", "pronouncs": "chazak" },
    { "english": "weak", "hebrew": "חלש", "pronouncs": "chalash" },
    { "english": "long", "hebrew": "ארוך", "pronouncs": "aroch" },
    { "english": "short", "hebrew": "קצר", "pronouncs": "ketzar" },
    { "english": "healthy", "hebrew": "בריא", "pronouncs": "bari" },
    { "english": "sick", "hebrew": "חולה", "pronouncs": "choleh" },
    { "english": "expensive", "hebrew": "יקר", "pronouncs": "yakar" },
    { "english": "cheap", "hebrew": "זול", "pronouncs": "zol" },
    { "english": "slim", "hebrew": "רזה", "pronouncs": "razeh" },
    { "english": "fat", "hebrew": "שמן", "pronouncs": "shemen" },
    { "english": "new", "hebrew": "חדש", "pronouncs": "chadash" },
    { "english": "old", "hebrew": "ישן", "pronouncs": "yshan" },
    { "english": "sweet", "hebrew": "מתוק", "pronouncs": "matok" },
    { "english": "salty", "hebrew": "מלוח", "pronouncs": "maloach" },
    { "english": "tall/high", "hebrew": "גבוה", "pronouncs": "gavoah" },
    { "english": "low", "hebrew": "נמוך", "pronouncs": "namuch" },
    { "english": "I/he eat", "hebrew": "אוכל", "pronouncs": "ochel" },
    { "english": "I/he drink", "hebrew": "שותה", "pronouncs": "shoteh" },
    { "english": "I/he live", "hebrew": "גר", "pronouncs": "gar" },
    { "english": "I/he studie", "hebrew": "לומד", "pronouncs": "lomed" },
    { "english": "I/he talk/speak", "hebrew": "מדבר", "pronouncs": "medaber" },
    { "english": "I/he doe/make", "hebrew": "עושה", "pronouncs": "oseh" },
    { "english": "I/he read/call", "hebrew": "קורא", "pronouncs": "koreh" },
    { "english": "I/he think", "hebrew": "חושב", "pronouncs": "choshev" },
    { "english": "I/he write", "hebrew": "כותב", "pronouncs": "kotev" },
    { "english": "I/he understand", "hebrew": "מבין", "pronouncs": "mevin" },
    { "english": "I/he want", "hebrew": "רוצה", "pronouncs": "rotzeh" },
    { "english": "I/he ask", "hebrew": "שואל", "pronouncs": "sho'el" },
    { "english": "I/he say", "hebrew": "אומר", "pronouncs": "omer" },
    { "english": "I/he count", "hebrew": "סופר", "pronouncs": "sofer" },
    { "english": "I/he go/walk", "hebrew": "הולך", "pronouncs": "holech" },
    { "english": "I/he return", "hebrew": "חוזר", "pronouncs": "chozech" },
    { "english": "I/he drive/ride/travel", "hebrew": "נוסע", "pronouncs": "noseaa" },
    { "english": "I/he run", "hebrew": "רץ", "pronouncs": "ratz" },
    { "english": "I/he (get/wake) up", "hebrew": "קם", "pronouncs": "kam" },
    { "english": "I/he hear", "hebrew": "שומע", "pronouncs": "shomeaa" },
    { "english": "I/he come", "hebrew": "בא", "pronouncs": "ba" },
    { "english": "I/he invite/order", "hebrew": "מזמין", "pronouncs": "mazmin" },
    { "english": "I/he feel", "hebrew": "מרגיש", "pronouncs": "margish" },
    { "english": "I/he see", "hebrew": "רואה", "pronouncs": "ro'eh" },
    { "english": "I/he dance", "hebrew": "רוקד", "pronouncs": "roked" },
    { "english": "I/he sing", "hebrew": "שר", "pronouncs": "shar" },
    { "english": "I/he request", "hebrew": "מבקש", "pronouncs": "mevakesh" },
    { "english": "I/he give", "hebrew": "נותן", "pronouncs": "noten" },
    { "english": "I/he meet", "hebrew": "פוגש", "pronouncs": "pogesh" },
    { "english": "I/he can", "hebrew": "יכול", "pronouncs": "yachol" },
    { "english": "I/he hurt/pain", "hebrew": "כואב", "pronouncs": "ko'ev" },
    { "english": "I/he rest", "hebrew": "נח", "pronouncs": "nach" },
    { "english": "I/he choose", "hebrew": "בוחר", "pronouncs": "bocher" },
    { "english": "I/he wear", "hebrew": "מתלבש", "pronouncs": "mitlabesh" },
    { "english": "I/he find", "hebrew": "מוצא", "pronouncs": "motze" },
    { "english": "I/he dream", "hebrew": "חולם", "pronouncs": "cholem" },
    { "english": "I/he opene", "hebrew": "פותח", "pronouncs": "poteach" },
    { "english": "I/he close", "hebrew": "סוגר", "pronouncs": "soger" },
    { "english": "I/he stand", "hebrew": "עומד", "pronouncs": "omed" },
    { "english": "I/he buie", "hebrew": "קונה", "pronouncs": "koneh" },
    { "english": "I/he put", "hebrew": "שם", "pronouncs": "sam" },
    { "english": "I/he build", "hebrew": "בונה", "pronouncs": "boneh" },
    { "english": "I/he go up/rises", "hebrew": "עולה", "pronouncs": "oleh" },
    { "english": "I/he go down", "hebrew": "יורד", "pronouncs": "yored" },
    { "english": "I/he answer", "hebrew": "עונה", "pronouncs": "oneh" },
    { "english": "I/he exit/leave", "hebrew": "יוצא", "pronouncs": "yotze" },
    { "english": "I/he take", "hebrew": "לוקח", "pronouncs": "lokeach" },
    { "english": "I/he sit", "hebrew": "יושב", "pronouncs": "yoshev" },
    { "english": "I/he pray", "hebrew": "מתפלל", "pronouncs": "metpalel" },
    { "english": "I/he play music", "hebrew": "מנגן", "pronouncs": "menagen" },
    { "english": "I/he organize/arrange", "hebrew": "מסדר", "pronouncs": "mesader" },
    { "english": "I/he tell a story", "hebrew": "מספר", "pronouncs": "mesaper" },
    { "english": "I/he photograph/film", "hebrew": "מצלם", "pronouncs": "metzalem" },
    { "english": "I/he play", "hebrew": "משחק", "pronouncs": "mesachek" },
    { "english": "I/he arrive", "hebrew": "מגיע", "pronouncs": "magiaa" },
    { "english": "I/he argue", "hebrew": "רב", "pronouncs": "rav" },
    { "english": "I/he flie (airplane)", "hebrew": "טס", "pronouncs": "tas" },
    { "english": "money/silver", "hebrew": "כסף", "pronouncs": "kesef" },
    { "english": "but", "hebrew": "אבל", "pronouncs": "aval" },
    { "english": "now", "hebrew": "עכשיו", "pronouncs": "achshav" },
    { "english": "people", "hebrew": "אנשים", "pronouncs": "anashim" },
    { "english": "here", "hebrew": "פה/כאן", "pronouncs": "pu/kan" },
    { "english": "lot", "hebrew": "הרבה", "pronouncs": "harbeh" },
    { "english": "children", "hebrew": "ילדים", "pronouncs": "yeladim" },
    { "english": "at all", "hebrew": "בכלל", "pronouncs": "bechlal" },
    { "english": "apartment", "hebrew": "דירה", "pronouncs": "dira" },
    { "english": "stuff", "hebrew": "דברים", "pronouncs": "dvarim" },
    { "english": "store", "hebrew": "חנות", "pronouncs": "chanut" },
    { "english": "next to", "hebrew": "ליד", "pronouncs": "liad" },
    { "english": "plan/program", "hebrew": "תוכנית", "pronouncs": "tochnit" },
    { "english": "tomorrow", "hebrew": "מחר", "pronouncs": "machar" },
    { "english": "cat", "hebrew": "חתול", "pronouncs": "chatul" },
    { "english": "very", "hebrew": "מאוד", "pronouncs": "me'od" },
    { "english": "car", "hebrew": "מכונית", "pronouncs": "mechonit" },
    { "english": "never", "hebrew": "אף פעם", "pronouncs": "af paam" },
    { "english": "enough", "hebrew": "מספיק", "pronouncs": "maspik" },
    { "english": "question", "hebrew": "שאלה", "pronouncs": "she'elah" },
    { "english": "tired", "hebrew": "עיף", "pronouncs": "aaif" },
    { "english": "yesterday", "hebrew": "אתמול", "pronouncs": "etmol" },
    { "english": "day before yesterday", "hebrew": "שלשום", "pronouncs": "shelshom" },
    { "english": "how long", "hebrew": "כמה זמן", "pronouncs": "kama zman" },
    { "english": "there", "hebrew": "שם", "pronouncs": "sham" },
    { "english": "day", "hebrew": "יום", "pronouncs": "yom" },
    { "english": "after", "hebrew": "אחרי", "pronouncs": "acharei" },
    { "english": "in/while/(after a period of time)", "hebrew": "בעוד", "pronouncs": "be'od" },
    { "english": "vacation", "hebrew": "חופשה", "pronouncs": "chofsha" },
    { "english": "event", "hebrew": "אירוע", "pronouncs": "eroaa" },
    { "english": "half", "hebrew": "חצי", "pronouncs": "chetzi" },
    { "english": "important", "hebrew": "חשוב", "pronouncs": "chashuv" },
    { "english": "simple", "hebrew": "פשות", "pronouncs": "pashut" },
    { "english": "interesting", "hebrew": "מעניין", "pronouncs": "maanyen" },
    { "english": "hard", "hebrew": "קשה", "pronouncs": "kasheh" },
    { "english": "easy", "hebrew": "קל", "pronouncs": "kal" },
    { "english": "I/he hope", "hebrew": "מקווה", "pronouncs": "mekaveh" },
    { "english": "pretty", "hebrew": "יפה", "pronouncs": "yafeh" },
    { "english": "party", "hebrew": "מסיבה", "pronouncs": "mesiba" },
    { "english": "excellent", "hebrew": "מצוין", "pronouncs": "metzoyan" },
    { "english": "amazing", "hebrew": "מעולה", "pronouncs": "maa'oleh" },
    { "english": "all", "hebrew": "כל", "pronouncs": "kol" },
    { "english": "bus", "hebrew": "אוטובוס", "pronouncs": "otobus" },
    { "english": "morning", "hebrew": "בוקר", "pronouncs": "boker" },
    { "english": "sea", "hebrew": "ים", "pronouncs": "yam" },
    { "english": "restaurant", "hebrew": "מסעדה", "pronouncs": "mesaada" },
    { "english": "I/he work", "hebrew": "עובד", "pronouncs": "oved" },
    { "english": "airport", "hebrew": "שדה תעופה", "pronouncs": "sadeh te'ofa" },
    { "english": "kita", "hebrew": "גן ילדים", "pronouncs": "gan yeladim" },
    { "english": "french", "hebrew": "צרפתית", "pronouncs": "tzrfatit" },
    { "english": "france", "hebrew": "צרפת", "pronouncs": "tzrfat" },
    { "english": "spanish", "hebrew": "ספרדית", "pronouncs": "sfardit" },
    { "english": "spain", "hebrew": "ספרד", "pronouncs": "sfarad" },
    { "english": "german", "hebrew": "גרמנית", "pronouncs": "germanit" },
    { "english": "germany", "hebrew": "גרמניה", "pronouncs": "germania" },
    { "english": "russian", "hebrew": "רוסית", "pronouncs": "rusit" },
    { "english": "russia", "hebrew": "רוסיה", "pronouncs": "rusia" },
    { "english": "noon", "hebrew": "צהריים", "pronouncs": "tzaraym" },
    { "english": "afternoon", "hebrew": "אחר הצהריים", "pronouncs": "achar hatzaraym" },
    { "english": "evining", "hebrew": "ערב", "pronouncs": "erev" },
    { "english": "meal", "hebrew": "ארוחה", "pronouncs": "arucha" },
    { "english": "breakfast", "hebrew": "ארוחת בוקר", "pronouncs": "aruchat boker" },
    { "english": "wine", "hebrew": "יין", "pronouncs": "yaen" },
    { "english": "beer", "hebrew": "בירה", "pronouncs": "bira" },
    { "english": "they call", "hebrew": "קוראים", "pronouncs": "kor'im" },
    { "english": "some/a little bit/ not much", "hebrew": "קצת", "pronouncs": "ktzat" },
    { "english": "few", "hebrew": "כמה", "pronouncs": "kama" },
    { "english": "to where", "hebrew": "לאן", "pronouncs": "le'an" },
    { "english": "park", "hebrew": "פארק", "pronouncs": "park" },
    { "english": "mall", "hebrew": "קניון", "pronouncs": "kanion" },
    { "english": "to drive", "hebrew": "לנסוע", "pronouncs": "lensuaa" },
    { "english": "to go/walk", "hebrew": "ללכת", "pronouncs": "lalecht" },
    { "english": "to work", "hebrew": "לעבוד", "pronouncs": "la'avod" },
    { "english": "cinema", "hebrew": "קולנוע", "pronouncs": "kolnoaa" },
    { "english": "grocery store", "hebrew": "מכולת", "pronouncs": "makolet" },
    { "english": "to enter/get in", "hebrew": "להיכנס", "pronouncs": "lehikanes" },
    { "english": "I/he enter/get in", "hebrew": "נכנס", "pronouncs": "nechnas" },
    { "english": "to hurt", "hebrew": "לכאוב", "pronouncs": "lech'ov" },
    { "english": "to rest", "hebrew": "לנוח", "pronouncs": "lanoach" },
    { "english": "to choose", "hebrew": "לבחור", "pronouncs": "levchor" },
    { "english": "to wear", "hebrew": "להתלבש", "pronouncs": "lehitlabseh" },
    { "english": "to find", "hebrew": "למצוא", "pronouncs": "lemtzo" },
    { "english": "to dream", "hebrew": "לחלום", "pronouncs": "lachlom" },
    { "english": "to open", "hebrew": "לפתוח", "pronouncs": "leftoach" },
    { "english": "to close", "hebrew": "לסגור", "pronouncs": "leskor" },
    { "english": "to stand", "hebrew": "לעמוד", "pronouncs": "la'amud" },
    { "english": "to buy", "hebrew": "לקנות", "pronouncs": "leknot" },
    { "english": "to put", "hebrew": "לשים", "pronouncs": "lasim" },
    { "english": "to build", "hebrew": "לבנות", "pronouncs": "levnot" },
    { "english": "to rise/go up", "hebrew": "לעלות", "pronouncs": "la'alot" },
    { "english": "to answer", "hebrew": "לענות", "pronouncs": "la'anot" },
    { "english": "to exit/leave", "hebrew": "לצאת", "pronouncs": "latzet" },
    { "english": "to take", "hebrew": "לקחת", "pronouncs": "lakachat" },
    { "english": "to sit", "hebrew": "לשבת", "pronouncs": "lashevet" },
    { "english": "to pray", "hebrew": "להתפלל", "pronouncs": "lahetpalel" },
    { "english": "to play music", "hebrew": "לנגן", "pronouncs": "lenagen" },
    { "english": "to organize/arrange", "hebrew": "לסדר", "pronouncs": "lesader" },
    { "english": "to tell a story", "hebrew": "לספר", "pronouncs": "lesaper" },
    { "english": "to film/photograph", "hebrew": "לצלם", "pronouncs": "letzalem" },
    { "english": "to play", "hebrew": "לשחק", "pronouncs": "lesachek" },
    { "english": "to arrive", "hebrew": "להגיע", "pronouncs": "lehagiaa" },
    { "english": "to argue", "hebrew": "לריב", "pronouncs": "lariv" },
    { "english": "to fly (air plane)", "hebrew": "לטוס", "pronouncs": "latus" },
    { "english": "to speak/talk", "hebrew": "לדבר", "pronouncs": "ledaber" },
    { "english": "to study", "hebrew": "ללמוד", "pronouncs": "lelmod" },
    { "english": "to want", "hebrew": "לרצות", "pronouncs": "lertzot" },
    { "english": "to help", "hebrew": "לעזור", "pronouncs": "la'azor" },
    { "english": "I/he help", "hebrew": "עוזר", "pronouncs": "ozer" },
    { "english": "to love", "hebrew": "לאהוב", "pronouncs": "le'hov" },
    { "english": "I/he love", "hebrew": "אוהב", "pronouncs": "ohev" },
    { "english": "to ask", "hebrew": "לשאול", "pronouncs": "lesh'ol" },
    { "english": "phone", "hebrew": "טלפון", "pronouncs": "telephone" },
    { "english": "answer(n)", "hebrew": "תשובה", "pronouncs": "tshova" },
    { "english": "to eat", "hebrew": "לאכול", "pronouncs": "le'echol" },
    { "english": "hungry", "hebrew": "רעב", "pronouncs": "ra'ev" },
    { "english": "satiated", "hebrew": "שבע", "pronouncs": "saveaa" },
    { "english": "food", "hebrew": "אוכל", "pronouncs": "ochel" },
    { "english": "salad", "hebrew": "סלט", "pronouncs": "salat" },
    { "english": "bon appetite", "hebrew": "בתאבון", "pronouncs": "betiavon" },
    { "english": "to drink", "hebrew": "לשתות", "pronouncs": "leshtot" },
    { "english": "thirsty", "hebrew": "צמא", "pronouncs": "tzame" },
    { "english": "color", "hebrew": "צבע", "pronouncs": "tzevaa" },
    { "english": "red", "hebrew": "אדם", "pronouncs": "adom" },
    { "english": "yellow", "hebrew": "צהב", "pronouncs": "tzahov" },
    { "english": "green", "hebrew": "ירק", "pronouncs": "yarok" },
    { "english": "blue", "hebrew": "כחל", "pronouncs": "kachol" },
    { "english": "light blue", "hebrew": "תכלת", "pronouncs": "techelet" },
    { "english": "purple", "hebrew": "סגל", "pronouncs": "sagol" },
    { "english": "orange (color)", "hebrew": "כתם", "pronouncs": "katom" },
    { "english": "pink", "hebrew": "ורד", "pronouncs": "varod" },
    { "english": "burgundy", "hebrew": "בורדו", "pronouncs": "bordo" },
    { "english": "brown", "hebrew": "חום", "pronouncs": "chum" },
    { "english": "gray", "hebrew": "אפר", "pronouncs": "afor" },
    { "english": "gold", "hebrew": "זהב", "pronouncs": "zahav" },
    { "english": "copper", "hebrew": "נחשת", "pronouncs": "nechoshet" },
    { "english": "hair", "hebrew": "שער", "pronouncs": "se'ar" },
    { "english": "head", "hebrew": "ראש", "pronouncs": "rosh" },
    { "english": "chest", "hebrew": "חזה", "pronouncs": "chazeh" },
    { "english": "arm", "hebrew": "זרוע", "pronouncs": "zroaa" },
    { "english": "stomach", "hebrew": "בטן", "pronouncs": "beten" },
    { "english": "leg", "hebrew": "רגל", "pronouncs": "regel" },
    { "english": "face", "hebrew": "פנים", "pronouncs": "panim" },
    { "english": "eyebrows", "hebrew": "גבות", "pronouncs": "gabot" },
    { "english": "eye", "hebrew": "עין", "pronouncs": "a'ayn" },
    { "english": "nose", "hebrew": "אף", "pronouncs": "af" },
    { "english": "mouth", "hebrew": "פה", "pronouncs": "peh" },
    { "english": "lips", "hebrew": "שפתים", "pronouncs": "shfataym" },
    { "english": "teeth", "hebrew": "שנים", "pronouncs": "shenaym" },
    { "english": "tongue", "hebrew": "לשון", "pronouncs": "lashon" },
    { "english": "key", "hebrew": "מפתח", "pronouncs": "meftach" },
    { "english": "wide", "hebrew": "רחב", "pronouncs": "rachav" },
    { "english": "young", "hebrew": "צעיר", "pronouncs": "tza'ir" },

]

